HOST: http://api.twitter.com/
      
---
Twitter API 3.0
Welcome to our API. Comments support Markdown syntax
---

-- Retrieve Tweets --
GET /tweets
> Accept: application/json
< 200
< Content-Type: application/json
{ "items": [
  { "url": "/feed", "range":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }